import { ThemeProvider } from "next-themes"
import '../styles/global.css'
export const metadata = {
  title: process.env.NEXT_PUBLIC_SITE_TITLE,
  description: 'Generated by Next.js',
  icons: {
    icon: '/favicon.ico',
  }
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          enableSystem={true}
          attribute="class"
        >
          {/* Layout UI */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}