import { ThemeProvider } from "next-themes"
import '../styles/global.css'

export const metadata = {
  title: process.env.NEXT_PUBLIC_SITE_TITLE,
  description: 'Generated by Next.js',
  icons: {
    icon: '/favicon.ico',
  },
  openGraph: {
    images: [`https://og-image.now.sh/${encodeURI(
      process.env.NEXT_PUBLIC_SITE_TITLE
    )}.png?theme=light&md=0&fontSize=75px&images=https%3A%2F%2Fassets.vercel.com%2Fimage%2Fupload%2Ffront%2Fassets%2Fdesign%2Fnextjs-black-logo.svg`],
    title: process.env.NEXT_PUBLIC_SITE_TITLE,
    twitter: {
      card: 'summary_large_image',
    },
  },
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          enableSystem={true}
          attribute="class"
          defaultTheme="light"
        >
          {/* Layout UI */}
          {children}
        </ThemeProvider>
      </body>
    </html>
  )
}